// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEsdPBOoiaY7Pr6-d2LHvyb30N3XzqH88',
    appId: '1:742700902793:android:9ec95f868b394d1d26d958',
    messagingSenderId: '742700902793',
    projectId: 'fir-tutorial-be3d8',
    storageBucket: 'fir-tutorial-be3d8.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeAbGnTr1rKdQ5XhTVwcxpeZlrlIrAw9Y',
    appId: '1:742700902793:web:66c107d7520f15a526d958',
    messagingSenderId: '742700902793',
    projectId: 'fir-tutorial-be3d8',
    authDomain: 'fir-tutorial-be3d8.firebaseapp.com',
    storageBucket: 'fir-tutorial-be3d8.appspot.com',
    measurementId: 'G-8NHGZWXJCK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApwAeTL3KWyhNOU6SM2Li1KeLbojNcG-w',
    appId: '1:742700902793:ios:8b53271e2e11a05626d958',
    messagingSenderId: '742700902793',
    projectId: 'fir-tutorial-be3d8',
    storageBucket: 'fir-tutorial-be3d8.appspot.com',
    androidClientId: '742700902793-2be10l0d1lv6osmrh7c3vq6srhv5a1hq.apps.googleusercontent.com',
    iosClientId: '742700902793-0t82pn292q87rk3gjv7tmvk16d4p0k3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApwAeTL3KWyhNOU6SM2Li1KeLbojNcG-w',
    appId: '1:742700902793:ios:8b53271e2e11a05626d958',
    messagingSenderId: '742700902793',
    projectId: 'fir-tutorial-be3d8',
    storageBucket: 'fir-tutorial-be3d8.appspot.com',
    androidClientId: '742700902793-2be10l0d1lv6osmrh7c3vq6srhv5a1hq.apps.googleusercontent.com',
    iosClientId: '742700902793-0t82pn292q87rk3gjv7tmvk16d4p0k3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeAbGnTr1rKdQ5XhTVwcxpeZlrlIrAw9Y',
    appId: '1:742700902793:web:aa6f8077ffdbd68b26d958',
    messagingSenderId: '742700902793',
    projectId: 'fir-tutorial-be3d8',
    authDomain: 'fir-tutorial-be3d8.firebaseapp.com',
    storageBucket: 'fir-tutorial-be3d8.appspot.com',
    measurementId: 'G-7NVC7QZ7VC',
  );

}